on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build_guide:
    runs-on: ubuntu-latest
    name: build_native
    steps:
      - uses: actions/checkout@v2
        with:
          repository: chris-y/rman
      - name: build_rman
        id: build_rman
        run: make -f Makefile
      - uses: actions/upload-artifact@v1
        with:
          name: rman
          path: ./rman
      - uses: actions/checkout@v2
      - name: Download rman
        uses: actions/download-artifact@v1
        with:
          name: rman
      - name: build_guide
        id: build_guide
        run: |
          chmod a+x ./rman/rman
          make -f Makefile
      - uses: actions/upload-artifact@v1
        with:
          name: zmakebas.guide
          path: ./zmakebas.guide
  build_ppc:
    runs-on: ubuntu-latest
    container:
      image: amigadev/crosstools:ppc-amigaos
    name: build_os4
    steps:
      - uses: actions/checkout@v2
      - name: build_os4
        id: build_os4
        run: make -f Makefile zmakebas
      - uses: actions/upload-artifact@v1
        with:
          name: zmakebas_os4
          path: zmakebas
  build_68k:
    runs-on: ubuntu-latest
    container:
      image: walkero/docker4amigavbcc:latest-m68k
    name: build_os3
    steps:
      - uses: actions/checkout@v2
      - name: buildos3
        id: buildos3
        run: make -f Makefile.os3 zmakebas
      - uses: actions/upload-artifact@v1
        with:
          name: zmakebas_os3
          path: zmakebas
